services:
    doctrine_extra.orm.event_listener.cache_entity:
        class: PhpSolution\Doctrine\ORM\EventListener\CacheEntityListener
        public: false

    doctrine_extra.form_type.cache_entity:
        class: PhpSolution\Doctrine\Form\Type\CachedEntityType
        arguments: ['@doctrine', '@property_accessor']
        tags:
            - { name: form.type, alias: cached_entity }